export const FETCH_CURRENT_SONG = 'FETCH_CURRENT_SONG';
export const FETCH_SONGS_FROM_PLAYLIST = 'FETCH_SONGS_FROM_PLAYLIST';
export const FETCH_SONGS_SEARCH = 'FETCH_SONGS_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
